### ISSUE TITLE
No support for JVM properties and environment variables

### ISSUE THREAD

**Issue by etki** [cfg4j/cfg4j#128]
Hi.

I couldn't find any documentation reference for including JVM properties and good old environment variables as configuration source. Due to the popularization of Docker philosophy and 12-factor application concept it would be quite nice to provide library users with simple way to use both sources in their apps. I've already found a workaround with InMemoryConfigurationSource (and i know that documentation will become confusing the very moment it will specify word 'environment' in two meanings), however, i feel that is necessary to update library in that way (or at least mention InMemoryConfigurationSource workaround in documentation).

**Comment by norbertpotocki** [comment]
That's a good catch. JVM and environment properties are not supported as of now. I'll try to add it soon.

**Comment by fromanator** [comment]
This would be super helpful to have, since it would allow for easy integration with [12 Factor Application Configuration conventions](http://12factor.net/config). For the _EnvironmentVariableSource_ it would make sense for the Environment to define the prefixed namespace for the Environment Variables that you are interested in.

For example if you had and application name foo, with configurable properties bar and baz, you would format your environment in the following manner:
FOO_BAR="value"
FOO_BAZ="value"

Thus if you have the Environment context set to **FOO** then I would expect the _EnvironmentVariableSource_ would only return: BAR and BAZ along with their corresponding value.

Let me know what you think. I wouldn't mind working on implementing this feature since, selfishly, this would be very useful for what I need to do. I am looking into using [envconsul](https://github.com/hashicorp/envconsul) to insert the config from Consul and Environment variables, instead of using the ConsulConfigurationSource. I figured this will be much more flexible since we have applications not running on a JVM (like nodeJS) and this would provide a more consistent way to configure applications from Consul.

**Comment by norbertpotocki** [comment]
I like this approach a lot. Thanks for working on it.

**Comment by norbertpotocki** [comment]
@etki this is now supported by cfg4j version 4.3.0 :)

**Comment by etki** [comment]
@norbertpotocki  YARRR
